//AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_START = 'AUTH_START'


//ROOMS
export const SET_SELECTED_ROOM = 'SET_SELECTED_ROOM'
export const JOIN_ERROR = 'JOIN_ERROR'
export const JOIN_SUCCESS = 'JOIN_SUCCESS'
export const REMOVE_REDIRECT = 'REMOVE_REDIRECT'
export const JOIN_START = 'JOIN_START'
export const SET_ROOMS = 'SET_ROOMS'
export const SET_ROOM_USERS = 'SET_ROOM_USERS'
export const SEND_ERROR = 'SEND_ERROR'
export const SEND_SUCCESS = 'SEND_SUCCESS'
export const SET_MESSAGES = "SET_MESSAGES"
export const MY_MESSAGE_LOADING = 'MY_MESSAGE_LOADING'